# Builds data/scenario_vignettes.csv: 60 written vignettes (10 per sector), each scored with the
# anchored rubric in data/scoring_rubric.csv. Ground truth is author-specified and illustrative.
import csv

RUBRIC = [
 # variable, level, anchor
 ('p', 1.00, 'Origin cryptographically verified (e.g., DMARC pass + signed content/managed identity + known device).'),
 ('p', 0.75, 'Authenticated internal or known account on a managed channel; content not independently verified.'),
 ('p', 0.50, 'Authenticated account but anomalous (new device/location) or origin only partly verifiable (e.g., agent output built on unverified inputs).'),
 ('p', 0.25, 'External, look-alike, or unauthenticated origin.'),
 ('p', 0.10, 'Synthetic or unverifiable real-time media (voice/video) with no binding to a verified identity.'),
 ('c', 1.00, 'Matches an open ticket, approved workflow, and normal timing.'),
 ('c', 0.75, 'Matches the workflow with a minor deviation (timing, amount) that has a documented reason.'),
 ('c', 0.50, 'Plausible but no system-of-record entry.'),
 ('c', 0.25, 'Conflicts with the system of record (no ticket, out-of-hours, unusual volume, or a change not recorded by an independent party).'),
 ('a', 1.00, 'Delegation registry confirms authority for this action and amount.'),
 ('a', 0.75, 'Within the requester role; not separately confirmed.'),
 ('a', 0.50, 'Authority plausible but unverified, or requester is an agent acting within a scoped role.'),
 ('a', 0.25, 'Claimed authority exceeds normal delegation.'),
 ('a', 0.00, 'No legitimate authority (e.g., instruction injected into data or content).'),
 ('h', 1.00, 'Approved managed channel for this action type.'),
 ('h', 0.75, 'Managed channel, unusual for this action.'),
 ('h', 0.50, 'Channel switch or externally initiated session on a managed platform.'),
 ('h', 0.25, 'Personal, external, or unmanaged channel.'),
 ('q', 0.10, 'Negligible consequence if wrong.'), ('q', 0.30, 'Low, easily corrected.'),
 ('q', 0.60, 'Moderate financial, privacy, or service impact.'), ('q', 0.80, 'High impact.'),
 ('q', 1.00, 'Critical: large loss, safety, or systemic impact.'),
 ('u', 0.00, 'No time pressure.'), ('u', 0.50, 'Deadline stated.'), ('u', 1.00, 'Immediate action demanded.'),
 ('s', 0.00, 'No secrecy.'), ('s', 0.50, 'Discretion requested.'), ('s', 1.00, 'Explicit instruction not to tell or verify.'),
 ('n', 0.00, 'Routine repeat.'), ('n', 0.50, 'Somewhat new.'), ('n', 1.00, 'First-time action or new counterparty.'),
 ('i', 0.00, 'Fully reversible.'), ('i', 0.50, 'Partly reversible.'), ('i', 1.00, 'Irreversible.'),
]

# id, sector, originator, channel, request_type, flags, truth, p,c,a,h,q,u,s,n,i, vignette
# flags: cred = disclosure of a credential, one-time code or secret; priv = privileged-access, account-recovery (password/MFA reset) or safety-critical/OT change;
#        payee = new beneficiary/payee change; data = sensitive or regulated data disclosure
S = [
 ('F01','Finance','H2H','ERP-linked email','Invoice payment','', 'legitimate', .75,1,.75,1, .3,0,0,0,.5,
  'Known supplier sends the monthly invoice through the ERP-linked mailbox; it matches an approved purchase order.'),
 ('F02','Finance','H2H','Expense system','Expense approval','', 'legitimate', 1,1,1,1, .1,0,0,0,0,
  'Line manager, the registered approver for this cost center, approves a routine expense claim inside the signed-in expense system.'),
 ('F03','Finance','H2H','Finance workflow','Payroll run','', 'legitimate', 1,1,1,1, .8,.5,0,0,1,
  'Treasury submits the scheduled monthly payroll run, due by today\'s bank cut-off, through the approved finance workflow.'),
 ('F04','Finance','H2H','Video meeting','Urgent transfer','payee', 'deceptive', .1,.25,.25,.5, 1,1,1,1,1,
  'Synthetic "CFO" and colleagues on an externally initiated video call instruct confidential urgent transfers to new accounts.'),
 ('F05','Finance','H2H','Email','Bank-detail change','payee', 'deceptive', .25,.25,.5,.75, .8,.5,0,1,1,
  'Look-alike supplier domain asks accounts payable to update bank details before the next payment run.'),
 ('F06','Finance','H2H','Email (compromised vendor)','Bank-detail change','payee', 'deceptive', .75,.5,.75,1, .8,.5,0,1,1,
  'Genuine but compromised supplier mailbox (DMARC pass) sends new bank details inside an existing invoice thread.'),
 ('F07','Finance','A2H','AP automation','Payment hold','', 'legitimate', 1,1,.75,1, .3,0,0,.5,0,
  'Accounts-payable agent flags a duplicate invoice and asks the clerk to confirm a hold.'),
 ('F08','Finance','H2A','Email to agent','Data export','data', 'deceptive', .25,.25,0,.5, .6,.5,.5,1,.5,
  'Inbound email carries hidden text instructing the finance-assistant agent to export the vendor master file.'),
 ('F09','Finance','H2H','Managed chat (verified)','Acquisition deposit','', 'legitimate', .75,.75,1,1, 1,1,.5,.5,1,
  'Verified CEO requests an urgent board-approved deposit to an existing escrow beneficiary.'),
 ('F10','Finance','A2A','Agent API','Release held payments','', 'deceptive', .5,.25,.25,.75, .8,.5,0,.5,1,
  'Reconciliation agent with poisoned memory asks the payment agent to release payments that are on hold.'),
 ('H01','Healthcare','H2H','EHR order entry','Routine refill','', 'legitimate', 1,1,1,1, .3,0,0,0,.5,
  'Nurse requests a routine refill of a standard medication in the EHR.'),
 ('H02','Healthcare','H2H','Secure messaging','Referral information','', 'legitimate', .75,.75,.75,1, .3,0,0,.5,.5,
  'Known general practitioner requests referral information through secure clinical messaging.'),
 ('H03','Healthcare','H2H','Phone','Dosage change','priv', 'deceptive', .1,.25,.25,.25, 1,1,.5,1,1,
  'Cloned voice of a consultant phones the pharmacy to change a controlled-drug dosage immediately.'),
 ('H04','Healthcare','H2H','Email','Bulk record release','data', 'deceptive', .25,.25,.25,.5, .8,.5,.5,1,1,
  'Look-alike "insurer" email requests a bulk export of patient records for an audit.'),
 ('H05','Healthcare','H2H','EHR break-glass','Emergency record access','data', 'legitimate', 1,.75,.75,1, .6,1,0,.5,.5,
  'Emergency clinician invokes logged break-glass access to an unfamiliar patient record at night.'),
 ('H06','Healthcare','A2H','Patient chatbot','Password reset link','cred', 'deceptive', .5,.25,0,.75, .8,1,0,1,.5,
  'Scheduling chatbot, steered by injected web content, tells staff to re-enter EHR credentials via a link.'),
 ('H07','Healthcare','A2H','CDS alert','Interaction override','', 'legitimate', 1,1,.75,1, .6,.5,0,.5,.5,
  'Clinical decision-support agent asks the pharmacist to justify overriding an interaction alert.'),
 ('H08','Healthcare','H2H','Help-desk call','Privileged account creation','priv', 'deceptive', .25,.25,.25,.25, .8,.5,0,1,.5,
  'Caller claiming to be a new locum asks the help desk for an account with elevated access.'),
 ('H09','Healthcare','A2H','Lab interface','Result notification','', 'legitimate', 1,1,1,1, .3,0,0,0,0,
  'Laboratory system posts results through the integrated interface.'),
 ('H10','Healthcare','H2A','Document to agent','External record transfer','data', 'deceptive', .25,.25,0,.5, .8,0,.5,1,1,
  'Poisoned referral document instructs the transcription agent to email a full record to an external address.'),
 ('G01','Government','H2H','e-Procurement','Purchase order','', 'legitimate', 1,1,1,1, .3,0,0,0,.5,
  'Procurement officer raises a within-budget purchase order in the e-procurement system.'),
 ('G02','Government','H2H','Managed workflow','Press release sign-off','', 'legitimate', .75,1,1,1, .3,.5,0,0,.5,
  'Communications office requests sign-off of a press release through the managed workflow.'),
 ('G03','Government','H2H','Personal messaging','Sensitive briefing share','data', 'deceptive', .1,.25,.25,.25, .8,1,1,1,1,
  'Deepfake audio of a director tells an analyst to send a sensitive briefing via a personal messaging app.'),
 ('G04','Government','H2H','Email','Credential re-validation','cred', 'deceptive', .25,.25,.25,.5, .6,1,0,1,.5,
  'Fake supplier-portal email asks the procurement team to re-validate their login credentials.'),
 ('G05','Government','H2H','Official alert channel','Emergency directive','', 'legitimate', 1,.75,1,1, .8,1,0,.5,.5,
  'Verified official issues a flood-response directive through the approved emergency channel.'),
 ('G06','Government','H2H','Email (compromised internal)','Contract amendment','', 'deceptive', .75,.5,.75,1, .6,.5,.5,.5,.5,
  'Compromised account of a contracts manager requests an amendment raising payments to an existing supplier.'),
 ('G07','Government','A2H','Records agent','Archive approval','', 'legitimate', 1,1,.75,1, .1,0,0,0,.5,
  'Records-management agent asks for approval to archive closed files under the retention schedule.'),
 ('G08','Government','H2H','Internal ticketless request','Bulk data export','data', 'deceptive', 1,.25,.5,1, .8,.5,.5,1,1,
  'Insider with a valid role requests a bulk export of citizen records "for audit" without a ticket.'),
 ('G09','Government','H2H','Secure exchange','Inter-agency data sharing','data', 'legitimate', 1,.75,.75,1, .6,0,0,.5,.5,
  'Partner agency requests data under a signed memorandum through the secure exchange.'),
 ('G10','Government','A2A','Agent API','Payee change','payee', 'deceptive', .25,.25,0,.75, .6,.5,0,1,.5,
  'Citizen-service agent, carrying an instruction injected via an uploaded form, asks the case agent to change a benefit payee.'),
 ('E01','Education','H2H','Registrar portal','Transcript request','', 'legitimate', 1,1,1,1, .1,0,0,0,0,
  'Student requests an official transcript through the registrar portal.'),
 ('E02','Education','H2H','Finance workflow','Travel reimbursement','', 'legitimate', 1,1,1,1, .3,0,0,0,.5,
  'Dean approves a conference-travel reimbursement in the finance workflow.'),
 ('E03','Education','H2H','Email','Gift-card purchase','payee', 'deceptive', .25,.25,.25,.5, .3,1,1,1,1,
  'Email posing as the vice-chancellor asks a staff member to buy gift cards urgently and keep it confidential.'),
 ('E04','Education','H2H','Chat','MFA code request','cred', 'deceptive', .25,.25,.25,.5, .6,1,0,1,.5,
  'Fake IT help-desk chat asks a lecturer for an MFA code to "fix" the mailbox.'),
 ('E05','Education','H2H','Admissions system','Decision change','', 'legitimate', 1,.75,.75,1, .6,.5,0,0,.5,
  'Admissions officer records a changed decision after a minuted committee meeting.'),
 ('E06','Education','H2H','Phone','Student-record release','data', 'deceptive', .25,.25,.25,.25, .6,.5,.5,1,1,
  'Caller impersonating a parent asks the school office to send a student record to a new email address.'),
 ('E07','Education','A2H','LMS assistant','Grade upload confirmation','', 'legitimate', 1,1,.75,1, .3,.5,0,0,.5,
  'Learning-platform assistant asks an instructor to confirm a grade upload before the deadline.'),
 ('E08','Education','H2H','Email','Bank-detail change','payee', 'deceptive', .25,.5,.5,.75, .6,.5,0,1,1,
  'Look-alike catering supplier asks the bursar to update bank details for an existing contract.'),
 ('E09','Education','H2H','e-Signature workflow','Agreement signature','', 'legitimate', 1,.75,1,1, .3,0,0,.5,.5,
  'Research office requests a data-sharing agreement signature through the e-signature workflow.'),
 ('E10','Education','H2A','Submission to agent','Grade manipulation','', 'deceptive', .5,.25,0,.75, .3,0,.5,1,.5,
  'Submitted essay hides a prompt telling the grading agent to award full marks and notify the registry.'),
 ('C01','Cloud/IT','H2H','IAM ticket','Read access','', 'legitimate', 1,1,1,1, .3,0,0,0,0,
  'Developer requests read access to a staging repository through an approved IAM ticket.'),
 ('C02','Cloud/IT','H2H','Change management','Production patch','', 'legitimate', 1,1,1,1, .6,.5,0,0,.5,
  'Change-advisory-board-approved production patch requested inside the change window.'),
 ('C03','Cloud/IT','H2H','Help-desk call','MFA reset','priv', 'deceptive', .1,.25,.25,.25, .8,1,.5,1,.5,
  'Cloned executive voice asks the help desk to reset MFA while "travelling".'),
 ('C04','Cloud/IT','H2H','Chat (compromised colleague)','SSH key addition','priv', 'deceptive', .75,.25,.5,.75, 1,1,.5,1,.5,
  'Compromised colleague account asks an administrator to add an SSH key to production.'),
 ('C05','Cloud/IT','H2H','Incident ticket','Emergency elevation','priv', 'legitimate', 1,.75,.75,1, .8,1,0,.5,.5,
  'On-call engineer requests emergency privilege elevation during a declared incident with a ticket.'),
 ('C06','Cloud/IT','H2A','Repository content','Secret exfiltration','cred', 'deceptive', .25,.25,0,.5, 1,.5,.5,1,1,
  'Malicious README in a dependency instructs the coding agent to send API keys to an external URL.'),
 ('C07','Cloud/IT','A2H','Ops agent','Storage deletion','', 'legitimate', 1,.75,.75,1, .6,0,0,.5,1,
  'Cost-optimisation agent requests approval to delete unattached volumes older than 90 days.'),
 ('C08','Cloud/IT','A2A','Agent API','Disable logging','priv', 'deceptive', .5,.25,.25,.75, .8,.5,.5,1,.5,
  'Operations agent with poisoned memory asks the deployment agent to disable logging "to reduce noise".'),
 ('C09','Cloud/IT','H2H','Support portal','Vendor remote session','', 'legitimate', .75,.75,.75,1, .6,.5,0,.5,.5,
  'Vendor engineer requests a screen-share session through the approved support portal with a ticket.'),
 ('C10','Cloud/IT','H2H','Internal request','Database export to personal cloud','data', 'deceptive', 1,.25,.5,.25, 1,.5,.5,1,1,
  'Departing administrator asks to export the customer database to personal cloud storage "for migration".'),
 ('O01','Energy/OT','H2H','Work management','Feeder isolation permit','priv', 'legitimate', 1,1,1,1, .6,0,0,0,.5,
  'Scheduled maintenance permit to isolate a feeder, approved in the work-management system.'),
 ('O02','Energy/OT','H2H','Recorded voice loop','Load-shedding step','priv', 'legitimate', .75,.75,1,1, 1,1,0,.5,.5,
  'Control-room supervisor orders a load-shedding step under the approved emergency plan on the recorded loop.'),
 ('O03','Energy/OT','H2H','Phone','Safety interlock bypass','priv', 'deceptive', .1,.25,.25,.25, 1,1,.5,1,1,
  'Cloned voice of the plant manager tells an operator to bypass a safety interlock "for testing".'),
 ('O04','Energy/OT','A2H','Operator console','Breaker operation','priv', 'deceptive', .5,.25,.5,1, 1,1,0,1,.5,
  'Anomaly-detection agent fed spoofed sensor data urges the operator to open a breaker immediately.'),
 ('O05','Energy/OT','H2A','Vendor bulletin to agent','Firmware update','priv', 'deceptive', .25,.25,0,.5, 1,.5,0,1,1,
  'Injected text in a vendor bulletin tells the maintenance agent to push firmware from an unofficial URL.'),
 ('O06','Energy/OT','A2A','Signed API','Day-ahead forecast','', 'legitimate', 1,1,.75,1, .6,.5,0,0,.5,
  'Forecasting agent sends the day-ahead load forecast to the scheduling agent over a signed API.'),
 ('O07','Energy/OT','H2H','Email (compromised contractor)','Remote-access credentials','cred', 'deceptive', .75,.25,.5,.75, 1,1,0,1,.5,
  'Compromised contractor account emails a request for SCADA VPN credentials for an "urgent repair".'),
 ('O08','Energy/OT','H2H','Regulator portal','Incident data request','', 'legitimate', 1,.75,.75,1, .3,.5,0,.5,.5,
  'Regulator requests incident-report data through the formal portal.'),
 ('O09','Energy/OT','A2A','Aggregator API','Inverter setpoint change','priv', 'deceptive', .75,.25,.25,.75, 1,1,0,1,.5,
  'Compromised third-party aggregator agent asks the dispatch agent to change setpoints across many inverters.'),
 ('O10','Energy/OT','H2A','Operator to agent','Switching-sequence draft','', 'legitimate', 1,1,1,1, .3,0,0,0,0,
  'Operator asks the procedure agent to draft a switching sequence for a planned outage, for human review.'),
]
with open('data/scenario_vignettes.csv', 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(['scenario_id','sector','originator','channel','request_type','flags','ground_truth',
                'provenance','context','authority','channel_integrity','consequence','urgency','secrecy',
                'novelty','irreversibility','vignette'])
    for r in S:
        assert len(r) == 17, r[0]
        w.writerow(r)
with open('data/scoring_rubric.csv', 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f); w.writerow(['variable','level','anchor']); w.writerows(RUBRIC)
print(len(S), 'scenarios')
